site_name: Auth0 AppSync React ハンズオン
theme: "material"
extra_css:
  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "css/custom.css"
extra:
  font:
    text: "Noto Sans JP"
    code: "Consolas"
markdown_extensions: 
  - admonition
  - codehilite
nav:
  - 環境構築:
      setup/cloud9.md
  - ハンズオン:
    - Reactでサンプルアプリを構築する: hands-on/react/react.md